const services = [
  {
    id: 1,
    icon: '/src/assets/emergency.png',
    nameBn: 'জাতীয় জরুরি সেবা',
    nameEn: 'National Emergency',
    contactNumber: '999',
    category: ['সার্বজনীন'],
  },
  {
    id: 2,
    icon: '/src/assets/police.png',
    nameBn: 'পুলিশ',
    nameEn: 'Police',
    contactNumber: '999',
    category: ['পুলিশ'],
  },
  {
    id: 3,
    icon: '/src/assets/fire-service.png',
    nameBn: 'ফায়ার সার্ভিস',
    nameEn: 'Fire Service',
    contactNumber: '999',
    category: ['ফায়ার'],
  },
  {
    id: 4,
    icon: '/src/assets/ambulance.png',
    nameBn: 'অ্যাম্বুলেন্স',
    nameEn: 'Ambulance',
    contactNumber: '1994-999999',
    category: ['স্বাস্থ্য'],
  },
  {
    id: 5,
    icon: '/src/assets/emergency.png',
    nameBn: 'নারী ও শিশু সহায়তা',
    nameEn: 'Women & Child Helpline',
    contactNumber: '109',
    category: ['সহায়তা'],
  },
  {
    id: 6,
    icon: '/src/assets/emergency.png',
    nameBn: 'দুদক',
    nameEn: 'Anti-Corruption',
    contactNumber: '106',
    category: ['সরকারি'],
  },
  {
    id: 7,
    icon: '/src/assets/emergency.png',
    nameBn: 'বিদ্যুৎ বিভ্রাট',
    nameEn: 'Electricity Outage',
    contactNumber: '16216',
    category: ['বিদ্যুৎ'],
  },
  {
    id: 8,
    icon: '/src/assets/emergency.png',
    nameBn: 'ব্র্যাক',
    nameEn: 'Brac',
    contactNumber: '16445',
    category: ['এনজিও'],
  },
  {
    id: 9,
    icon: '/src/assets/emergency.png',
    nameBn: 'বাংলাদেশ রেলওয়ে',
    nameEn: 'Bangladesh Railway',
    contactNumber: '163',
    category: ['পরিবহন'],
  },
];

